### ISSUE TITLE
CRITICAL: could not find parser 'csgo': check you main config file (b3.xml)

### ISSUE THREAD

**Issue by DavidRayner** [BigBrotherBot/big-brother-bot#328]
Getting this fatal error when using the latest files.

**Comment by danielepantaleone** [comment]
Could you please post your B3 log file? Make sure to mask your passwords first.

**Comment by DavidRayner** [comment]
Got it working now.

I used to run B3 successfully over half a year a go.

Since then you've dropped python2.6 support and as I'm on centOS I had to build python2.7 myself.
Python worked fine, however the python packages were not present in the 2.7 installation which caused the issue I posted here.

To solve the problem I copied the site-packages directory from python 2.6 into 2.7. I imagine this may cause issues for certain packages, but I believe it is working as solution for now.

Thanks.

**Comment by danielepantaleone** [comment]
We dropped support for python 2.6 since we are going to release Frozen builds for all the major platforms (win32, osx and linux). The Frozen app will have a python 2.7 environment shipped within the executables so it makes no sense to keep supporting python 2.6 (also debian now ships python 2.7 as default, not sure about centOS
