### ISSUE TITLE
B3 fails to update database

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#332]
with daily383:

![image](https://cloud.githubusercontent.com/assets/42300/7787745/b6337c12-021c-11e5-8e37-835938be77d6.png)

The command run is: `C:\BigBrotherBot\b3_run.exe --config "C:\BigBrotherBot\conf\b3.ini" --update`

**Comment by danielepantaleone** [comment]
right, gotta append --console to the shortcut

**Comment by thomasleveil** [comment]
not working :( same error

**Comment by danielepantaleone** [comment]
I'll have a deeper look then

**Comment by danielepantaleone** [comment]
Alright, it seems that this happens because there is no Command Prompt open and thus raw_input doesn't know where to get the input from. This is due the fact that the `setup.py` script declares the Executable base as Win32GUI instead of console application. Actually I read on stack overflow that it should be possible to fallback into console mode (http://stackoverflow.com/a/2882079) but apparently this is not working (the problem happens on Windows only, since on OSX the base is declared as None and fallbacks to console correctly). I guess the easiest way (easier also for the user) is to implement the setup and update procedure inside the GUI (maybe the setup is not necessary since we have the B3 config generator webtool, but an update procedure would be needed).

**Comment by thomasleveil** [comment]
I was just thinking that too. We should focus on the web config generator as it is less costly to develop, maintain and test.

**Comment by danielepantaleone** [comment]
I can port it in python and make it available through the GUI, but I guess it would be pointless to have a duplicate feature

**Comment by thomasleveil** [comment]
Sorry I thought this was #333, for the update feature we cannot rely on any web solution.

**Comment by danielepantaleone** [comment]
Yes, I thought I posted in #332 too but I didn't apparently.

**Comment by danielepantaleone** [comment]
I implemented the update feature here: https://github.com/BigBrotherBot/big-brother-bot/commit/612638aa10368952d4d98e92991b1f099969e30a
I pushed it into a separate branch since the old console update feature it's still there and I guess before menring I should update it too, trying to avoid duplicated code.
Also we would need to decide what to do with #333 (remove or not remove the console setup procedure) before merging.
