### ISSUE TITLE
Error: Could not parse line no such group

### ISSUE THREAD

**Issue by donna30urt** [BigBrotherBot/big-brother-bot#415]
Quite strange, this happens from time to time for clients connecting to my server, they're unable to use any commands at all and are therefore ignored. 

Case:
200706 20:55:58 CONSOLE  '2:44 say: 3 ^2F ^3a ^1d ^0l: !money'

200706 20:55:58 ERROR    'Could not parse line no such group: 
[(\'/home/urt2/big-brother-bot-1.12/b3/parser.py\', 1167, \'run\', \'self.parseLine(line)\'),
(\'/home/urt2/big-brother-bot-1.12/b3/parsers/q3a/abstractParser.py\', 213, \'parseLine\', \'event = func(action, data, match)\'), (\'/home/urt2/big-brother-bot-1.12/b3/parsers/iourt41.py\', 815, \'OnSay\', "name = self.stripColors(match.group(\'name\'))")]'

**Comment by 82ndab-Bravo17** [comment]
Did you alter the groups table from the default at all?

**Comment by donna30urt** [comment]
I haven't touched them

**Comment by danielepantaleone** [comment]
I believe the **group** the log is referring to is the regular expression captured group. Are you by any chance using custom server engine?

**Comment by donna30urt** [comment]
I am indeed using a modified server engine

**Comment by danielepantaleone** [comment]
Probably the server engine you are using is printing the log file differently, and B3 cannot recognize the Say event from which to extract the command.

**Comment by donna30urt** [comment]
Well that is only happening sometimes, especially if the client reconnects it's working just fine

**Comment by donna30urt** [comment]
Should I post the log of the client connecting when it works and also when it doesn't?

**Comment by danielepantaleone** [comment]
It would help 😊

**Comment by donna30urt** [comment]
https://paste.anonvodka.xyz/ukokilitil.py

there you go, it's quite a lot and I'm not sure what you will need so I rather post everything

The first time "fadl" connects it's not letting him use commands but when he reconnected it does

**Comment by donna30urt** [comment]
Another thing that I just found is that if the client renames it also works.. so /reconnect or renaming fixes this

**Comment by danielepantaleone** [comment]
The problem is that the user has spaces in his nickname and the B3 parser does not take space into consideration (because spaces, and if I recall correctly also color codes, are stripped by the server engine or the qvm). Since you are using a customized server engine (and possible also a modded qvm) you should fix this problem on your end.

[Parsing with spaces](https://pythex.org/?regex=%5E(%3FP%3Caction%3E%5Ba-z%5D%2B)%3A%5Cs(%3FP%3Cdata%3E(%3FP%3Ccid%3E%5B0-9%5D%2B)%5Cs(%3FP%3Cname%3E%5B%5E%20%5D%2B)%3A%5Cs*(%3FP%3Ctext%3E.*))%24&test_string=say%3A%203%20%5E2F%20%5E3a%20%5E1d%20%5E0l%3A%20!money&ignorecase=0&multiline=0&dotall=0&verbose=0)
[Parsing without spaces](https://pythex.org/?regex=%5E(%3FP%3Caction%3E%5Ba-z%5D%2B)%3A%5Cs(%3FP%3Cdata%3E(%3FP%3Ccid%3E%5B0-9%5D%2B)%5Cs(%3FP%3Cname%3E%5B%5E%20%5D%2B)%3A%5Cs*(%3FP%3Ctext%3E.*))%24&test_string=say%3A%203%20%5E2F%5E3a%5E1d%5E0l%3A%20!money&ignorecase=0&multiline=0&dotall=0&verbose=0)

**Comment by donna30urt** [comment]
Right I see, well I don't have access to the code of the server mod so I'll just find a workaround, probably by forcing a rename once a player connects. Thank you
Quick side question, can I somehow change how many commands per second b3 is able to send to the server?

**Comment by danielepantaleone** [comment]
I don't recall B3 specifying any delay in RCON commands. You may want to check if your server engine is limiting the amount of RCON commands in a given amount of time.
